export const hackerNewsMarkup: string = `<html op="news"><head><meta name="referrer" content="origin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" type="text/css" href="news.css?RPndN1NXMJWPrczzW0Wp">
<link rel="shortcut icon" href="favicon.ico">
<link rel="alternate" type="application/rss+xml" title="RSS" href="rss">
<title>Hacker News</title></head><body><center><table id="hnmain" border="0" cellpadding="0" cellspacing="0" width="85%" bgcolor="#f6f6ef">
<tr><td bgcolor="#ff6600"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="padding:2px"><tr><td style="width:18px;padding-right:4px"><a href="https://news.ycombinator.com"><img src="y18.gif" width="18" height="18" style="border:1px white solid;"></a></td>
      <td style="line-height:12pt; height:10px;"><span class="pagetop"><b class="hnname"><a href="news">Hacker News</a></b>
  <a href="newest">new</a> | <a href="front">past</a> | <a href="newcomments">comments</a> | <a href="ask">ask</a> | <a href="show">show</a> | <a href="jobs">jobs</a> | <a href="submit">submit</a>            </span></td><td style="text-align:right;padding-right:4px;"><span class="pagetop">
                  <a href="login?goto=news">login</a>
              </span></td>
  </tr></table></td></tr>
<tr id="pagespace" title="" style="height:10px"></tr><tr><td><table border="0" cellpadding="0" cellspacing="0" class="itemlist">
  <tr class='athing' id='19711756'>
<td align="right" valign="top" class="title"><span class="rank">1.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19711756' href='vote?id=19711756&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="http://lite.cnn.io/en/article/h_db08b33213d74c0d498afe6dc04c579c" class="storylink">Japan's Ainu will finally be recognized as indigenous people</a><span class="sitebit comhead"> (<a href="from?site=cnn.io"><span class="sitestr">cnn.io</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19711756">23 points</span> by <a href="user?id=Breadmaker" class="hnuser">Breadmaker</a> <span class="age"><a href="item?id=19711756">1 hour ago</a></span> <span id="unv_19711756"></span> | <a href="hide?id=19711756&amp;goto=news">hide</a> | <a href="item?id=19711756">discuss</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19711531'>
<td align="right" valign="top" class="title"><span class="rank">2.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19711531' href='vote?id=19711531&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.latimes.com/entertainment/herocomplex/la-et-hc-nintendo-game-boy-anniversary-20190421-story.html" class="storylink">At 30, Game Boys live on in unexpected ways</a><span class="sitebit comhead"> (<a href="from?site=latimes.com"><span class="sitestr">latimes.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19711531">49 points</span> by <a href="user?id=pseudolus" class="hnuser">pseudolus</a> <span class="age"><a href="item?id=19711531">3 hours ago</a></span> <span id="unv_19711531"></span> | <a href="hide?id=19711531&amp;goto=news">hide</a> | <a href="item?id=19711531">21&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19711257'>
<td align="right" valign="top" class="title"><span class="rank">3.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19711257' href='vote?id=19711257&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="http://blog.supertuxkart.net/2019/04/supertuxkart-10-release.html" class="storylink">SuperTuxKart 1.0 Release</a><span class="sitebit comhead"> (<a href="from?site=supertuxkart.net"><span class="sitestr">supertuxkart.net</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19711257">251 points</span> by <a href="user?id=shimabukuro" class="hnuser">shimabukuro</a> <span class="age"><a href="item?id=19711257">5 hours ago</a></span> <span id="unv_19711257"></span> | <a href="hide?id=19711257&amp;goto=news">hide</a> | <a href="item?id=19711257">40&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19707404'>
<td align="right" valign="top" class="title"><span class="rank">4.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19707404' href='vote?id=19707404&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://sci-hub.tw/10.2307/1429971" class="storylink">Germans Who Refused to Execute Civilians During World War II (1988) [pdf]</a><span class="sitebit comhead"> (<a href="from?site=sci-hub.tw"><span class="sitestr">sci-hub.tw</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19707404">53 points</span> by <a href="user?id=apsec112" class="hnuser">apsec112</a> <span class="age"><a href="item?id=19707404">4 hours ago</a></span> <span id="unv_19707404"></span> | <a href="hide?id=19707404&amp;goto=news">hide</a> | <a href="item?id=19707404">38&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19710288'>
<td align="right" valign="top" class="title"><span class="rank">5.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19710288' href='vote?id=19710288&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://ferd.ca/goodbye-joe.html" class="storylink">Goodbye Joe</a><span class="sitebit comhead"> (<a href="from?site=ferd.ca"><span class="sitestr">ferd.ca</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19710288">693 points</span> by <a href="user?id=mononcqc" class="hnuser">mononcqc</a> <span class="age"><a href="item?id=19710288">11 hours ago</a></span> <span id="unv_19710288"></span> | <a href="hide?id=19710288&amp;goto=news">hide</a> | <a href="item?id=19710288">16&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19710398'>
<td align="right" valign="top" class="title"><span class="rank">6.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19710398' href='vote?id=19710398&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://annehelen.substack.com/p/is-everything-an-mlm" class="storylink">It feels like everything today is a multi-level marketing scheme</a><span class="sitebit comhead"> (<a href="from?site=annehelen.substack.com"><span class="sitestr">annehelen.substack.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19710398">127 points</span> by <a href="user?id=colinprince" class="hnuser">colinprince</a> <span class="age"><a href="item?id=19710398">10 hours ago</a></span> <span id="unv_19710398"></span> | <a href="hide?id=19710398&amp;goto=news">hide</a> | <a href="item?id=19710398">47&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19709835'>
<td align="right" valign="top" class="title"><span class="rank">7.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19709835' href='vote?id=19709835&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.floridatoday.com/story/tech/science/space/2019/04/20/smoke-seen-miles-spacex-crew-dragon-suffers-anomaly-cape-canaveral/3531086002/" class="storylink">Smoke seen for miles as SpaceX Crew Dragon suffers anomaly at Cape Canaveral</a><span class="sitebit comhead"> (<a href="from?site=floridatoday.com"><span class="sitestr">floridatoday.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19709835">205 points</span> by <a href="user?id=jbuzbee" class="hnuser">jbuzbee</a> <span class="age"><a href="item?id=19709835">13 hours ago</a></span> <span id="unv_19709835"></span> | <a href="hide?id=19709835&amp;goto=news">hide</a> | <a href="item?id=19709835">112&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19711241'>
<td align="right" valign="top" class="title"><span class="rank">8.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19711241' href='vote?id=19711241&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://popula.com/2019/04/11/grandpas-beer/" class="storylink">Grandpa's Beer</a><span class="sitebit comhead"> (<a href="from?site=popula.com"><span class="sitestr">popula.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19711241">44 points</span> by <a href="user?id=neonate" class="hnuser">neonate</a> <span class="age"><a href="item?id=19711241">5 hours ago</a></span> <span id="unv_19711241"></span> | <a href="hide?id=19711241&amp;goto=news">hide</a> | <a href="item?id=19711241">16&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19709318'>
<td align="right" valign="top" class="title"><span class="rank">9.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19709318' href='vote?id=19709318&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.ias.edu/ideas/2012/george-dyson-ecp" class="storylink">An Artificially Created Universe: The Electronic Computer Project at IAS (2012)</a><span class="sitebit comhead"> (<a href="from?site=ias.edu"><span class="sitestr">ias.edu</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19709318">25 points</span> by <a href="user?id=benbreen" class="hnuser">benbreen</a> <span class="age"><a href="item?id=19709318">5 hours ago</a></span> <span id="unv_19709318"></span> | <a href="hide?id=19709318&amp;goto=news">hide</a> | <a href="item?id=19709318">discuss</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19711141'>
<td align="right" valign="top" class="title"><span class="rank">10.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19711141' href='vote?id=19711141&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://buckbuild.com/" class="storylink">Buck: A high-performance build tool</a><span class="sitebit comhead"> (<a href="from?site=buckbuild.com"><span class="sitestr">buckbuild.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19711141">24 points</span> by <a href="user?id=geezerjay" class="hnuser">geezerjay</a> <span class="age"><a href="item?id=19711141">5 hours ago</a></span> <span id="unv_19711141"></span> | <a href="hide?id=19711141&amp;goto=news">hide</a> | <a href="item?id=19711141">17&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19703488'>
<td align="right" valign="top" class="title"><span class="rank">11.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19703488' href='vote?id=19703488&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://medium.com/the-mission/a-genius-explains-how-to-be-creative-claude-shannons-long-lost-1952-speech-fbbcb2ebe07f" class="storylink">Claude Shannon’s “Creative Thinking” Speech (2017)</a><span class="sitebit comhead"> (<a href="from?site=medium.com"><span class="sitestr">medium.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19703488">114 points</span> by <a href="user?id=Hooke" class="hnuser">Hooke</a> <span class="age"><a href="item?id=19703488">11 hours ago</a></span> <span id="unv_19703488"></span> | <a href="hide?id=19703488&amp;goto=news">hide</a> | <a href="item?id=19703488">9&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19710835'>
<td align="right" valign="top" class="title"><span class="rank">12.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19710835' href='vote?id=19710835&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://en.wikipedia.org/wiki/X68000" class="storylink">Sharp X68000</a><span class="sitebit comhead"> (<a href="from?site=wikipedia.org"><span class="sitestr">wikipedia.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19710835">38 points</span> by <a href="user?id=peter_d_sherman" class="hnuser">peter_d_sherman</a> <span class="age"><a href="item?id=19710835">7 hours ago</a></span> <span id="unv_19710835"></span> | <a href="hide?id=19710835&amp;goto=news">hide</a> | <a href="item?id=19710835">8&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19710316'>
<td align="right" valign="top" class="title"><span class="rank">13.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19710316' href='vote?id=19710316&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.bbc.co.uk/news/health-47974844" class="storylink">A deaf girl who found her voice after brain surgery</a><span class="sitebit comhead"> (<a href="from?site=bbc.co.uk"><span class="sitestr">bbc.co.uk</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19710316">61 points</span> by <a href="user?id=JonEllis" class="hnuser">JonEllis</a> <span class="age"><a href="item?id=19710316">10 hours ago</a></span> <span id="unv_19710316"></span> | <a href="hide?id=19710316&amp;goto=news">hide</a> | <a href="item?id=19710316">7&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19699053'>
<td align="right" valign="top" class="title"><span class="rank">14.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19699053' href='vote?id=19699053&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.artnome.com/news/2019/4/17/giving-generative-art-its-due" class="storylink">Giving Generative Art Its Due</a><span class="sitebit comhead"> (<a href="from?site=artnome.com"><span class="sitestr">artnome.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19699053">52 points</span> by <a href="user?id=mathgenius" class="hnuser">mathgenius</a> <span class="age"><a href="item?id=19699053">10 hours ago</a></span> <span id="unv_19699053"></span> | <a href="hide?id=19699053&amp;goto=news">hide</a> | <a href="item?id=19699053">4&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19711567'>
<td align="right" valign="top" class="title"><span class="rank">15.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19711567' href='vote?id=19711567&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.bbc.co.uk/writersroom/scripts" class="storylink" rel="nofollow">Read BBC TV, Radio and Film scripts</a><span class="sitebit comhead"> (<a href="from?site=bbc.co.uk"><span class="sitestr">bbc.co.uk</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19711567">13 points</span> by <a href="user?id=open-source-ux" class="hnuser">open-source-ux</a> <span class="age"><a href="item?id=19711567">2 hours ago</a></span> <span id="unv_19711567"></span> | <a href="hide?id=19711567&amp;goto=news">hide</a> | <a href="item?id=19711567">1&nbsp;comment</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19708982'>
<td align="right" valign="top" class="title"><span class="rank">16.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19708982' href='vote?id=19708982&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="http://www.antenna-theory.com/" class="storylink">Antenna Theory (2016)</a><span class="sitebit comhead"> (<a href="from?site=antenna-theory.com"><span class="sitestr">antenna-theory.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19708982">288 points</span> by <a href="user?id=dosshell" class="hnuser">dosshell</a> <span class="age"><a href="item?id=19708982">16 hours ago</a></span> <span id="unv_19708982"></span> | <a href="hide?id=19708982&amp;goto=news">hide</a> | <a href="item?id=19708982">47&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19710747'>
<td align="right" valign="top" class="title"><span class="rank">17.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19710747' href='vote?id=19710747&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://twitter.com/hillelogram/status/1119709859979714560" class="storylink">Sleep quality and stress level matter more than languages or practices</a><span class="sitebit comhead"> (<a href="from?site=twitter.com"><span class="sitestr">twitter.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19710747">109 points</span> by <a href="user?id=ognyankulev" class="hnuser">ognyankulev</a> <span class="age"><a href="item?id=19710747">8 hours ago</a></span> <span id="unv_19710747"></span> | <a href="hide?id=19710747&amp;goto=news">hide</a> | <a href="item?id=19710747">18&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19710841'>
<td align="right" valign="top" class="title"><span class="rank">18.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19710841' href='vote?id=19710841&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://gizmodo.com/researchers-made-25-ton-boulders-they-can-move-by-hand-1834106230" class="storylink">Researchers Made 25-Ton Boulders They Can Move by Hand</a><span class="sitebit comhead"> (<a href="from?site=gizmodo.com"><span class="sitestr">gizmodo.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19710841">82 points</span> by <a href="user?id=mcenedella" class="hnuser">mcenedella</a> <span class="age"><a href="item?id=19710841">7 hours ago</a></span> <span id="unv_19710841"></span> | <a href="hide?id=19710841&amp;goto=news">hide</a> | <a href="item?id=19710841">20&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19711732'>
<td align="right" valign="top" class="title"><span class="rank">19.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19711732' href='vote?id=19711732&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://en.wikipedia.org/wiki/Ark_II" class="storylink">Ark II</a><span class="sitebit comhead"> (<a href="from?site=wikipedia.org"><span class="sitestr">wikipedia.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19711732">10 points</span> by <a href="user?id=BerislavLopac" class="hnuser">BerislavLopac</a> <span class="age"><a href="item?id=19711732">1 hour ago</a></span> <span id="unv_19711732"></span> | <a href="hide?id=19711732&amp;goto=news">hide</a> | <a href="item?id=19711732">3&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19709551'>
<td align="right" valign="top" class="title"><span class="rank">20.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19709551' href='vote?id=19709551&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.nytimes.com/2019/04/16/magazine/letter-of-recommendation-digging-a-trench.html" class="storylink">Letter of Recommendation: Digging a Trench</a><span class="sitebit comhead"> (<a href="from?site=nytimes.com"><span class="sitestr">nytimes.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19709551">55 points</span> by <a href="user?id=js2" class="hnuser">js2</a> <span class="age"><a href="item?id=19709551">14 hours ago</a></span> <span id="unv_19709551"></span> | <a href="hide?id=19709551&amp;goto=news">hide</a> | <a href="item?id=19709551">11&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19708620'>
<td align="right" valign="top" class="title"><span class="rank">21.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19708620' href='vote?id=19708620&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="http://neuralnetworksanddeeplearning.com/chap4.html" class="storylink">A visual proof that neural nets can approximate any continuous function</a><span class="sitebit comhead"> (<a href="from?site=neuralnetworksanddeeplearning.com"><span class="sitestr">neuralnetworksanddeeplearning.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19708620">286 points</span> by <a href="user?id=antman" class="hnuser">antman</a> <span class="age"><a href="item?id=19708620">17 hours ago</a></span> <span id="unv_19708620"></span> | <a href="hide?id=19708620&amp;goto=news">hide</a> | <a href="item?id=19708620">108&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19703745'>
<td align="right" valign="top" class="title"><span class="rank">22.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19703745' href='vote?id=19703745&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://en.wikipedia.org/wiki/Lion-Eating_Poet_in_the_Stone_Den" class="storylink">Lion-Eating Poet in the Stone Den</a><span class="sitebit comhead"> (<a href="from?site=wikipedia.org"><span class="sitestr">wikipedia.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19703745">42 points</span> by <a href="user?id=benbreen" class="hnuser">benbreen</a> <span class="age"><a href="item?id=19703745">13 hours ago</a></span> <span id="unv_19703745"></span> | <a href="hide?id=19703745&amp;goto=news">hide</a> | <a href="item?id=19703745">6&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19701279'>
<td align="right" valign="top" class="title"><span class="rank">23.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19701279' href='vote?id=19701279&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="http://pinksquirrellabs.com/blog/2019/04/17/fairylog/" class="storylink">Fairylog: A Racket language aiming to be like Verilog</a><span class="sitebit comhead"> (<a href="from?site=pinksquirrellabs.com"><span class="sitestr">pinksquirrellabs.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19701279">49 points</span> by <a href="user?id=setori88" class="hnuser">setori88</a> <span class="age"><a href="item?id=19701279">15 hours ago</a></span> <span id="unv_19701279"></span> | <a href="hide?id=19701279&amp;goto=news">hide</a> | <a href="item?id=19701279">16&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19709811'>
<td align="right" valign="top" class="title"><span class="rank">24.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19709811' href='vote?id=19709811&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://github.com/pichi-router/pichi" class="storylink">Show HN: Pichi – HTTP/Socks5/SS Proxy, Whose Route Controlled via APIs</a><span class="sitebit comhead"> (<a href="from?site=github.com"><span class="sitestr">github.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19709811">32 points</span> by <a href="user?id=pichi-router" class="hnuser">pichi-router</a> <span class="age"><a href="item?id=19709811">13 hours ago</a></span> <span id="unv_19709811"></span> | <a href="hide?id=19709811&amp;goto=news">hide</a> | <a href="item?id=19709811">6&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19705741'>
<td align="right" valign="top" class="title"><span class="rank">25.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19705741' href='vote?id=19705741&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://larrysanger.org/2019/04/vendors-must-start-adding-physical-on-off-switches-to-devices-that-can-spy-on-us/" class="storylink">Vendors must start adding physical on/off switches to devices that can spy on us</a><span class="sitebit comhead"> (<a href="from?site=larrysanger.org"><span class="sitestr">larrysanger.org</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19705741">396 points</span> by <a href="user?id=jrepinc" class="hnuser">jrepinc</a> <span class="age"><a href="item?id=19705741">1 day ago</a></span> <span id="unv_19705741"></span> | <a href="hide?id=19705741&amp;goto=news">hide</a> | <a href="item?id=19705741">170&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19708997'>
<td align="right" valign="top" class="title"><span class="rank">26.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19708997' href='vote?id=19708997&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://content.pivotal.io/blog/should-that-be-a-microservice-keep-these-six-factors-in-mind" class="storylink">Should that be a microservice? Factors to keep in mind</a><span class="sitebit comhead"> (<a href="from?site=pivotal.io"><span class="sitestr">pivotal.io</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19708997">175 points</span> by <a href="user?id=jbkavungal" class="hnuser">jbkavungal</a> <span class="age"><a href="item?id=19708997">16 hours ago</a></span> <span id="unv_19708997"></span> | <a href="hide?id=19708997&amp;goto=news">hide</a> | <a href="item?id=19708997">64&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19708778'>
<td align="right" valign="top" class="title"><span class="rank">27.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19708778' href='vote?id=19708778&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.youtube.com/watch?v=R3By_rdwxSg" class="storylink">Sinclair ZX81 1KB Chess vs. Stockfish Chess Engine (2018) [video]</a><span class="sitebit comhead"> (<a href="from?site=youtube.com"><span class="sitestr">youtube.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19708778">154 points</span> by <a href="user?id=cpeterso" class="hnuser">cpeterso</a> <span class="age"><a href="item?id=19708778">17 hours ago</a></span> <span id="unv_19708778"></span> | <a href="hide?id=19708778&amp;goto=news">hide</a> | <a href="item?id=19708778">24&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19710972'>
<td align="right" valign="top" class="title"><span class="rank">28.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19710972' href='vote?id=19710972&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://twitter.com/spdustin/status/1119118085443559425" class="storylink">NLP on Mueller Report</a><span class="sitebit comhead"> (<a href="from?site=twitter.com"><span class="sitestr">twitter.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19710972">84 points</span> by <a href="user?id=rahimnathwani" class="hnuser">rahimnathwani</a> <span class="age"><a href="item?id=19710972">6 hours ago</a></span> <span id="unv_19710972"></span> | <a href="hide?id=19710972&amp;goto=news">hide</a> | <a href="item?id=19710972">20&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19709475'>
<td align="right" valign="top" class="title"><span class="rank">29.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19709475' href='vote?id=19709475&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://www.youtube.com/watch?v=BXmOlCy0oBM" class="storylink">Erlang: The Movie [video]</a><span class="sitebit comhead"> (<a href="from?site=youtube.com"><span class="sitestr">youtube.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19709475">183 points</span> by <a href="user?id=pg_bot" class="hnuser">pg_bot</a> <span class="age"><a href="item?id=19709475">15 hours ago</a></span> <span id="unv_19709475"></span> | <a href="hide?id=19709475&amp;goto=news">hide</a> | <a href="item?id=19709475">6&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
    <tr class='athing' id='19708429'>
<td align="right" valign="top" class="title"><span class="rank">30.</span></td>      <td valign="top" class="votelinks"><center><a id='up_19708429' href='vote?id=19708429&amp;how=up&amp;goto=news'><div class='votearrow' title='upvote'></div></a></center></td><td class="title"><a href="https://gist.github.com/lizthegrey/9c21673f33186a9cc775464afbdce820" class="storylink">Hardening SSH with 2FA</a><span class="sitebit comhead"> (<a href="from?site=gist.github.com"><span class="sitestr">gist.github.com</span></a>)</span></td></tr><tr><td colspan="2"></td><td class="subtext">
<span class="score" id="score_19708429">169 points</span> by <a href="user?id=LanceTaylor" class="hnuser">LanceTaylor</a> <span class="age"><a href="item?id=19708429">18 hours ago</a></span> <span id="unv_19708429"></span> | <a href="hide?id=19708429&amp;goto=news">hide</a> | <a href="item?id=19708429">89&nbsp;comments</a>              </td></tr>
<tr class="spacer" style="height:5px"></tr>
<tr class="morespace" style="height:10px"></tr><tr><td colspan="2"></td><td class="title"><a href="news?p=2" class="morelink" rel="next">More</a></td></tr>
</table>
</td></tr>
<tr><td><img src="s.gif" height="10" width="0"><table width="100%" cellspacing="0" cellpadding="1"><tr><td bgcolor="#ff6600"></td></tr></table><br><center><span class="yclinks"><a href="newsguidelines.html">Guidelines</a>
| <a href="newsfaq.html">FAQ</a>
| <a href="mailto:hn@ycombinator.com">Support</a>
| <a href="https://github.com/HackerNews/API">API</a>
| <a href="security.html">Security</a>
| <a href="lists">Lists</a>
| <a href="bookmarklet.html" rel="nofollow">Bookmarklet</a>
| <a href="http://www.ycombinator.com/legal/">Legal</a>
| <a href="http://www.ycombinator.com/apply/">Apply to YC</a>
| <a href="mailto:hn@ycombinator.com">Contact</a></span><br><br><form method="get" action="//hn.algolia.com/">Search:
<input type="text" name="q" value="" size="17" autocorrect="off" spellcheck="false" autocapitalize="off" autocomplete="false"></form>
</center></td></tr>
</table></center></body><script type='text/javascript' src='hn.js?RPndN1NXMJWPrczzW0Wp'></script>
</html>
`;
